起動やコマンド実行を早くする
inukawaii/shirasu pull request #10
Opened 2020-02-11 08:48 UTC by inukawaii

cf: https://techracho.bpsinc.jp/hachi8833/2019_09_06/79035

2020-02-11 15:57 UTC, aksh-t requested changes
とりあえずコードを読んで気になったところをコメントしました。
これから動かしてみます。

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/.ruby-version
> +2.6.4
[IMO]
`.ruby-version` が2箇所にあるのは、バージョン変える時に問題になる可能性があるので、できればリポジトリルートのやつに統一したいです。

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/Aptfile
> +vim
[IMO]
要らないなら消したいですね。
(でもdockerコンテナ入った時にvim使えるのは便利かも🤔)

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/Dockerfile
> +ENV LANG=C.UTF-8 \
元ネタでは`GEM_HOME=/bundle\` を設定しているようですが、不要でしょうか？

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/Dockerfile
> +
元ネタではこの辺のPATH周りも設定していますが、不要でしょうか？
```
ENV BUNDLE_PATH $GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH\
  BUNDLE_BIN=$BUNDLE_PATH/bin
ENV PATH /app/bin:$BUNDLE_BIN:$PATH
```

2020-02-11 15:57 UTC, aksh-t commented on Dockerfile
> +ARG RUBY_VERSION
[IMO]
このDockerfile自体不要になる(=.dockerdev/Dockerfileに移行する)なら削除しませんか？

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +        YARN_VERSION: '1.13.0'
[IMO]
yarnのバージョンを最新にしたいです。

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +    image: martians-library-dev:1.1.0
[Question]
このイメージは何者なのでしょう？

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +    image: martians-library-dev:1.1.0
ざっくりした理解ですが、ここのimageオプションってbuildしたイメージに自分で名前をつける感じなのではないでしょうか？
なので、例えば`shirasu-dev`とかにすると良い気がします。

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +      - bundle:/usr/local/bundle
[Question]
元ネタでは`- bundle:/bundle`となっていますが、変更した理由を教えて欲しいです

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +      - NODE_ENV=development
[IMO]
元ネタ通り、`- NODE_ENV=${NODE_ENV:-development}`にしておいた方が、混乱しなくていいかと思います。
(実際は環境切り替えて使うことはないと思いますが。)

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
bundleのvolume定義を変更するならここも変更必要なので、変更するなら忘れずに。

2020-02-11 15:57 UTC, aksh-t commented on docker-compose.yml
> +      - WEB_CONCURRENCY=1
[IMO]
ここも元ネタ通りに`  - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}`にしておいて害はないのでは？
(実際には切り替えないけど。)

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/Dockerfile
> +
[IMO]
元ネタみる感じだと、ここ要らなそうなのですが、要りますか？

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/Dockerfile
> +    libpq-dev \
上のapt-getを消すなら、こちらに`build-essential`を追加する必要がありそうですね。

2020-02-11 15:57 UTC, aksh-t commented on .dockerdev/Dockerfile
> +    libpq-dev \
[Question]
あと`libpq-dev`は元ネタには記載ありませんでしたが、必要ですか？

2020-02-15 03:59 UTC, inukawaii commented on Dockerfile
> +ARG RUBY_VERSION
ですね！削除しました

2020-02-15 06:02 UTC, inukawaii commented on .dockerdev/Aptfile
> +vim
不要というほどのこともないかな〜と思うので、残したいです！

2020-02-15 06:02 UTC, inukawaii commented on .dockerdev/.ruby-version
> +2.6.4
別に誰も参照してないみたいなので消しました 🆑

2020-02-15 12:38 UTC, aksh-t approved these changes
node, yarnのバージョンはあげたいですが、いったんまーじしちゃいましょう

2020-02-15 12:38 UTC, merged